- name: confgure mysql server
  hosts: mysql
  become: yes
  tasks: 
  - name: Install Mysql libraries
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: Install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
        
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.sdaws-82s.online
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "MYSQL info: {{mysql_info}}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass Expense@1"
    when: mysql_info.failed is true           